### ISSUE TITLE
non-root user issue with getuid()

### ISSUE THREAD

**Issue by pescorilo** [iamseth/bash-syslog#1]
Hi,

I'm no C programmer, so please forgive me if this is not code-related issue.
My problem is that after patching bash code (bash-3.2-32) src rpm with your code, if I did su - limited-user or directly connected with the non-root user, on releasing a command it hanged with no way of closing the session.
I had a hunch that it is an access issue of some sort so I recompiled removing one-by-one the requests made by pathed bash when a limited user was issuing a command, and found that only the getuid() function is the cause.

Maybe you no longer use this, but it could be useful to solve the problem for others. For me it's OK with only getlogin() and getpid() and history string.

Regards.

**Comment by iamseth** [comment]
Thanks for the feedback. Sorry it's taken so long to respond. I wasn't getting email update for some reason and wasn't manually checking the issue list.

Are you still having this issue? If so, could you provide details about the system such as distro, version, etc?
