### ISSUE TITLE
Variable missmatch

### ISSUE THREAD

**Issue by electroniko** [iamseth/bash-syslog#2]
Hi, I used this patch and found an issue that can be easily fixed (I was using this for an old server after the bash security issue)

on uid  you have %s, and that vcauses to hang when executing any command, but just changing it to uid:%d fixes it (line 104 and 111)

**Comment by iamseth** [comment]
Thanks for the feedback and sorry for neglecting this issue. For some reason I wasn't getting email updates from GitHub for a while.

May I ask what version of Bash you had an issue with?

**Comment by electroniko** [comment]
Hey, no worries!

It was bash 3.2

**Comment by electroniko** [comment]
And this is my patch, based on yours:

diff -crB logbash-3.2/bashhist.c logbash-3.2.new/bashhist.c
**\* logbash-3.2/bashhist.c      Sat Sep 25 00:50:44 2010
--- logbash-3.2.new/bashhist.c  Sat Sep 25 00:50:58 2010

---

**\* 708,714 ****
  {
    hist_last_line_added = 1;
    hist_last_line_pushed = 0;
!   add_history (line);
    history_lines_this_session++;
  }

--- 708,714 ----
  {
    hist_last_line_added = 1;
    hist_last_line_pushed = 0;
!   add_history (line, 1);
    history_lines_this_session++;
  }

Only in logbash-3.2.new/: bashhist.c.ORIG
diff -crB logbash-3.2/lib/readline/histexpand.c logbash-3.2.new/lib/readline/histexpand.c
**\* logbash-3.2/lib/readline/histexpand.c       Sat Jul 29 16:44:17 2006
--- logbash-3.2.new/lib/readline/histexpand.c   Sat Sep 25 00:53:05 2010

---

**\* 1221,1227 ****
    if (only_printing)
      {
  #if 0
!       add_history (result);
  #endif
        return (2);
      }
--- 1221,1227 ----
    if (only_printing)
      {
  #if 0
!       add_history (result, 1);
  #endif
        return (2);
      }
Only in logbash-3.2.new/lib/readline: histexpand.c.ORIG
diff -crB logbash-3.2/lib/readline/histfile.c logbash-3.2.new/lib/readline/histfile.c
**\* logbash-3.2/lib/readline/histfile.c Fri Mar 31 15:48:43 2006
--- logbash-3.2.new/lib/readline/histfile.c     Sat Sep 25 00:53:38 2010

---

**\* 266,272 ****
          {
            if (HIST_TIMESTAMP_START(line_start) == 0)
              {
!               add_history (line_start);
                if (last_ts)
                  {
                    add_history_time (last_ts);
--- 266,272 ----
          {
            if (HIST_TIMESTAMP_START(line_start) == 0)
              {
!               add_history (line_start, 0);
                if (last_ts)
                  {
                    add_history_time (last_ts);
Only in logbash-3.2.new/lib/readline: histfile.c.ORIG
diff -crB logbash-3.2/lib/readline/history.c logbash-3.2.new/lib/readline/history.c
**\* logbash-3.2/lib/readline/history.c  Sun May 21 13:39:41 2006
--- logbash-3.2.new/lib/readline/history.c      Sat Sep 25 00:55:36 2010

---

**\* 42,49 ****
--- 42,52 ----
  #    include <sys/types.h>
  #  endif
  #  include <unistd.h>
- #endif
- #include <syslog.h>
- #include <pwd.h> 
  #include "history.h"
  #include "histlib.h"

---

**\* 262,272 ****
  /\* Place STRING at the end of the history list.  The data field
     is  set to NULL. */
  void
! add_history (string)
!      const char *string;
  {
    HIST_ENTRY *temp;

```
if (history_stifled && (history_length == history_max_entries))
  {
    register int i;
```

--- 265,302 ----
  /\* Place STRING at the end of the history list.  The data field
     is  set to NULL. */
  void
! add_history (const char *string, int logme)
  {
    HIST_ENTRY *temp;
-  struct passwd _pwd;
  +
  +/_ First let's see if the user has run sudo. If so his original username
- \*    will be in SUDO_USER variable. */
-  const char *sudo_user = getenv("SUDO_USER");
-    if (sudo_user == NULL) { /\* No he's not running sudo. Let's find out
-                                who he is */
-        if ((pwd = getpwuid(getuid())) != NULL)
-                sudo_user = pwd->pw_name;
-        else /\* We couldn't find his username by asking passwd. We'll have
-                to trust LOGNAME */
-                sudo_user = getenv("LOGNAME");
-    }
-   if (logme) {
-     if (strlen(string)<600) {
-       syslog(LOG_AUTHPRIV|LOG_INFO, "[user:%s sudo:%s pid:%d uid:%d euid:%d gid:%d egid:%d] %s",
-                            getlogin(), sudo_user, getpid(), getuid(), geteuid(), getgid(), getegid(), string);
-     } else {
-       char trunc[600];
-   
-       strncpy(trunc,string,sizeof(trunc));
-       trunc[sizeof(trunc)-1]='\0';
-        syslog(LOG_AUTHPRIV|LOG_INFO, "[user:%s sudo:%s pid:%d uid:%d euid:%d gid:%d egid:%d] %s(++TRUNC)",
-                            getlogin(), sudo_user, getpid(), getuid(), geteuid(), getgid(), getegid(), trunc);
-     }
-   }
- 
- if (history_stifled && (history_length == history_max_entries))
    {
      register int i;
  Only in logbash-3.2.new/lib/readline: history.c.ORG
  diff -crB logbash-3.2/lib/readline/history.h logbash-3.2.new/lib/readline/history.h
  **\* logbash-3.2/lib/readline/history.h  Thu Jul 31 08:38:44 2003
  --- logbash-3.2.new/lib/readline/history.h      Sat Sep 25 00:56:18 2010
  
  ---
  
  **\* 80,86 ****
  
  /\* Place STRING at the end of the history list.
     The associated data field (if any) is set to NULL. */
  ! extern void add_history PARAMS((const char *));
  
  /\* Change the timestamp associated with the most recent history entry to
     STRING. */
  --- 80,86 ----
  
  /\* Place STRING at the end of the history list.
     The associated data field (if any) is set to NULL. */
  ! extern void add_history PARAMS((const char *, int));
  
  /\* Change the timestamp associated with the most recent history entry to
     STRING. */
  Only in logbash-3.2.new/lib/readline: history.h.ORIG
